if [ "$DESKTOP_SESSION" =~ "xfce" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

if [ "$OSTYPE" =~ "darwin" ]
then
  export PATH=$HOME/Library/Python/3.8/bin:/opt/homebrew/opt/gnu-tar/libexec/gnubin/:/opt/homebrew/Cellar/coreutils/9.0/libexec/gnubin:/opt/homebrew/bin:$PATH
  export LC_CTYPE=UTF-8
fi

command -v vim >/dev/null 2>&1 && export EDITOR=vim
command -v nvim >/dev/null 2>&1 && export EDITOR=nvim

[ -d $HOME/workspace/git.rootknecht.net/scripts ] && export PATH=$PATH:$HOME/workspace/git.rootknecht.net/scripts
[ -d $HOME/.jenv/bin ] && export PATH=$PATH:$HOME/.jenv/bin
command -v jenv >/dev/null 2>&1 && eval "$(jenv init -)"
[ -d $HOME/.local/bin ] && export PATH=$PATH:$HOME/.local/bin
[ -d $HOME/.luarocks/bin ] && export PATH=$PATH:$HOME/.luarocks/bin
[ -f $HOME/.shell/aliases ] && source $HOME/.shell/aliases
[ -f $HOME/.shell/kubectl_aliases ] && source $HOME/.shell/kubectl_aliases
[ -f $HOME/.shell/funcs ] && source $HOME/.shell/funcs
[ -d $HOME/./shell/fzf-tab/ ] && source $HOME/.shell/fzf-tab/fzf-tab.plugin.zsh

export LF_ICONS="\
di=🗀 :\
fi=🗎:\
ln=:\
or=:\
ex=:\
*.vimrc=:\
*.viminfo=:\
*.gitignore=:\
*.c=:\
*.cc=:\
*.clj=:\
*.coffee=:\
*.cpp=:\
*.css=:\
*.d=:\
*.dart=:\
*.erl=:\
*.exs=:\
*.fs=:\
*.go=:\
*.h=:\
*.hh=:\
*.hpp=:\
*.hs=:\
*.html=:\
*.java=:\
*.jl=:\
*.js=:\
*.json=:\
*.lua=:\
*.md=:\
*.php=:\
*.pl=:\
*.pro=:\
*.py=:\
*.rb=:\
*.rs=:\
*.scala=:\
*.ts=:\
*.vim=:\
*.pdf=:\
*.nix=:\
"
