if [ "$DESKTOP_SESSION" =~ "xfce" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
[ -d $HOME/workspace/scripts ] && export PATH=$PATH:$HOME/workspace/scripts
[ -d $HOME/.local/bin ] && export PATH=$PATH:$HOME/.local/bin
[ -f $HOME/.shell/aliases ] && source $HOME/.shell/aliases
[ -f $HOME/.shell/kubectl_aliases ] && source $HOME/.shell/kubectl_aliases
[ -f $HOME/.shell/funcs ] && source $HOME/.shell/funcs
[ -d $HOME/./shell/fzf-tab/ ] && source $HOME/.shell/fzf-tab/fzf-tab.plugin.zsh
