#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff6e75f5
yabai -m config normal_window_border_color   0xffBCBDBF
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt # if this is cmd this prevents cmd + right mouse to select!
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       float
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   06
yabai -m config external_bar                 all:25:0 # padding top:bottom

# no tiling on space one
# BUT apps will not respect top padding for the bar
# yabai -m config --space 1 layout float

# Floating for special apps
yabai -m rule --add app="^KeePassXC$" sticky=off layer=normal manage=off
yabai -m rule --add app="^ForkLift$" sticky=off layer=normal manage=off
yabai -m rule --add app="^Font Book$" sticky=off layer=normal manage=off
yabai -m rule --add app="^System Preferences$" sticky=off layer=normal manage=off
yabai -m rule --add app="^TinkerTool$" sticky=off layer=normal manage=off
yabai -m rule --add app="^Docker Desktop$" sticky=off layer=normal manage=off

# Handling sketchybar window events
# yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
# yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."
