
require('packages')
require('mappings')
require('options')
require('globals')
require('autocmd')
require('plugins/kommentary')
require('plugins/reload')
require('plugins/telescope')
require('plugins/nvim-tree')
