#!/bin/sh
while read file
do
	case "$1" in
		"d") trash "$file" ;;
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
				notify-send "$file copied to clipboard" &
			;;
		"Y")
			echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" &
			;;
		"i")	ifinstalled gimp && gimp "$file" & ;;
	esac
done
